general:
  buildTool: 'npm'
  verbose: true
  
  vaultAppRoleTokenCredentialsId: 'tht-vault-approle-role-id'
  vaultAppRoleSecretTokenCredentialsId: 'tht-vault-approle-secret-id'
  vaultBasePath: 'piper/THT-PIPELINE-GROUP'
  vaultPipelineName: 'thanh-test-cxone-dev'
  vaultPath: 'piper/THT-PIPELINE-GROUP'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/sectest/checkmarxone/manualtesting'
  
steps:
  checkmarxOneExecuteScan:
    projectName: 'tht-reference-pipeline-node'
    groupName: 'tht-group1'
    presetName: 'Checkmarx Default'
    branchName: 'master'
    languageMode: 'primary'
    projectCriticality: 3
    serverUrl: 'https://checkmarx-dev.tools.sap'
    iamUrl:  'https://checkmarx-dev.tools.sap'
    tenant: 'sap-beta'
    incremental: false
    filterPattern:  '**/*, !**/*test*, !*.zip, !*.exe'
    generatePdfReport: true
